-- MatchMyMakeup — Phase 0 initial schema
-- Apply to staging first. Verify in Table Editor, then re-run on prod.
-- Idempotent: safe to re-run.

-- ============================================================================
-- profiles (1 row per auth.users, auto-created by trigger below)
-- ============================================================================
create table if not exists public.profiles (
  user_id                 uuid primary key references auth.users(id) on delete cascade,
  profile_dna             jsonb not null default '{}'::jsonb,
  country                 text,
  trial_started_at        timestamptz,
  last_scan_date          date,
  current_streak          int not null default 0,
  is_admin                boolean not null default false,
  stripe_customer_id      text unique,
  stripe_subscription_id  text unique,
  subscription_status     text,
  current_period_end      timestamptz,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

-- ============================================================================
-- scans
-- ============================================================================
create table if not exists public.scans (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  color_hex   text,
  skin_tone   text,
  occasion    text,
  country     text,
  category    text,
  advice      text,
  created_at  timestamptz not null default now()
);
create index if not exists scans_user_created_idx on public.scans (user_id, created_at desc);

-- ============================================================================
-- saved_shades
-- ============================================================================
create table if not exists public.saved_shades (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  name        text not null,
  hex         text not null,
  created_at  timestamptz not null default now()
);
create index if not exists saved_shades_user_idx on public.saved_shades (user_id);

-- ============================================================================
-- saved_products
-- Shade is nullable — not all entries have one. NULLS NOT DISTINCT means
-- two rows with shade=NULL for the same (user_id, name, brand) collide,
-- matching the client's existing dedup behaviour for user-added products.
-- ============================================================================
create table if not exists public.saved_products (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  name        text not null,
  brand       text,
  category    text,
  hex         text,
  shade       text,
  price       numeric(10,2),
  currency    text,
  rating      int check (rating between 1 and 5),
  notes       text,
  created_at  timestamptz not null default now(),
  unique nulls not distinct (user_id, name, brand, shade)
);
create index if not exists saved_products_user_idx on public.saved_products (user_id);

-- ============================================================================
-- saved_looks
-- ============================================================================
create table if not exists public.saved_looks (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  name        text not null,
  occasion    text,
  shades      text[] not null default '{}',
  created_at  timestamptz not null default now()
);
create index if not exists saved_looks_user_idx on public.saved_looks (user_id);

-- ============================================================================
-- Auto-update updated_at on profiles
-- ============================================================================
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists set_updated_at_on_profiles on public.profiles;
create trigger set_updated_at_on_profiles
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ============================================================================
-- Auto-create profile row on signup
-- ============================================================================
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
-- RLS — users see/edit own rows only. Service role bypasses all policies.
-- ============================================================================
alter table public.profiles       enable row level security;
alter table public.scans          enable row level security;
alter table public.saved_shades   enable row level security;
alter table public.saved_products enable row level security;
alter table public.saved_looks    enable row level security;

-- profiles (no DELETE policy — removal only via auth.users cascade)
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select using  (auth.uid() = user_id);
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = user_id);
create policy "profiles_update_own" on public.profiles for update using  (auth.uid() = user_id) with check (auth.uid() = user_id);

-- scans
drop policy if exists "scans_select_own" on public.scans;
drop policy if exists "scans_insert_own" on public.scans;
drop policy if exists "scans_update_own" on public.scans;
drop policy if exists "scans_delete_own" on public.scans;
create policy "scans_select_own" on public.scans for select using  (auth.uid() = user_id);
create policy "scans_insert_own" on public.scans for insert with check (auth.uid() = user_id);
create policy "scans_update_own" on public.scans for update using  (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "scans_delete_own" on public.scans for delete using  (auth.uid() = user_id);

-- saved_shades
drop policy if exists "saved_shades_select_own" on public.saved_shades;
drop policy if exists "saved_shades_insert_own" on public.saved_shades;
drop policy if exists "saved_shades_update_own" on public.saved_shades;
drop policy if exists "saved_shades_delete_own" on public.saved_shades;
create policy "saved_shades_select_own" on public.saved_shades for select using  (auth.uid() = user_id);
create policy "saved_shades_insert_own" on public.saved_shades for insert with check (auth.uid() = user_id);
create policy "saved_shades_update_own" on public.saved_shades for update using  (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "saved_shades_delete_own" on public.saved_shades for delete using  (auth.uid() = user_id);

-- saved_products
drop policy if exists "saved_products_select_own" on public.saved_products;
drop policy if exists "saved_products_insert_own" on public.saved_products;
drop policy if exists "saved_products_update_own" on public.saved_products;
drop policy if exists "saved_products_delete_own" on public.saved_products;
create policy "saved_products_select_own" on public.saved_products for select using  (auth.uid() = user_id);
create policy "saved_products_insert_own" on public.saved_products for insert with check (auth.uid() = user_id);
create policy "saved_products_update_own" on public.saved_products for update using  (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "saved_products_delete_own" on public.saved_products for delete using  (auth.uid() = user_id);

-- saved_looks
drop policy if exists "saved_looks_select_own" on public.saved_looks;
drop policy if exists "saved_looks_insert_own" on public.saved_looks;
drop policy if exists "saved_looks_update_own" on public.saved_looks;
drop policy if exists "saved_looks_delete_own" on public.saved_looks;
create policy "saved_looks_select_own" on public.saved_looks for select using  (auth.uid() = user_id);
create policy "saved_looks_insert_own" on public.saved_looks for insert with check (auth.uid() = user_id);
create policy "saved_looks_update_own" on public.saved_looks for update using  (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "saved_looks_delete_own" on public.saved_looks for delete using  (auth.uid() = user_id);
