-- MatchMyMakeup — migration 0002: wardrobe_items + subscription_tier
-- Applies after 0001_initial_schema.sql.
-- Idempotent: safe to re-run.

-- ============================================================================
-- profiles: add subscription_tier (free / premium / premium_plus)
-- Complements subscription_status from 0001 (Stripe state vs. price-level).
-- ============================================================================
alter table public.profiles
  add column if not exists subscription_tier text
    check (subscription_tier in ('free', 'premium', 'premium_plus'))
    default 'free';

-- ============================================================================
-- wardrobe_items (Premium+ tier — Personal Beauty Library)
-- photo_url expected to be a Supabase Storage URL. Bucket + bucket RLS
-- policies deferred to the migration that ships the upload UI (consistent
-- with D10's deferral of scan images).
-- ============================================================================
create table if not exists public.wardrobe_items (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references auth.users(id) on delete cascade,
  photo_url        text not null,
  item_type        text,
  dominant_colors  text[] not null default '{}',
  season           text,
  tags             text[] not null default '{}',
  notes            text,
  created_at       timestamptz not null default now()
);
create index if not exists wardrobe_items_user_idx on public.wardrobe_items (user_id);

-- ============================================================================
-- RLS — users see/edit own rows only. Service role bypasses all policies.
-- ============================================================================
alter table public.wardrobe_items enable row level security;

drop policy if exists "wardrobe_items_select_own" on public.wardrobe_items;
drop policy if exists "wardrobe_items_insert_own" on public.wardrobe_items;
drop policy if exists "wardrobe_items_update_own" on public.wardrobe_items;
drop policy if exists "wardrobe_items_delete_own" on public.wardrobe_items;
create policy "wardrobe_items_select_own" on public.wardrobe_items for select using  (auth.uid() = user_id);
create policy "wardrobe_items_insert_own" on public.wardrobe_items for insert with check (auth.uid() = user_id);
create policy "wardrobe_items_update_own" on public.wardrobe_items for update using  (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "wardrobe_items_delete_own" on public.wardrobe_items for delete using  (auth.uid() = user_id);
