// ── MatchMyMakeup Server-Side Product Matching ──────────────────────────────
// Product database and matching algorithm - never exposed to browser

const PRODUCTS = [
  // ── USA ──────────────────────────────────────────────────────────────────
  // Lipstick
  { id: "us_001", name: "Ruby Woo", brand: "MAC", category: "lipstick", hexCode: "#BB1C2B", red: 187, green: 28, blue: 43, colorName: "True Red", price: 21, currency: "USD", retailerUrl: "https://www.maccosmetics.com/product/13854/310/products/makeup/lips/lipstick/matte-lipstick", country: "USA" },
  { id: "us_002", name: "Velvet Teddy", brand: "MAC", category: "lipstick", hexCode: "#B07060", red: 176, green: 112, blue: 96, colorName: "Muted Beige Pink", price: 21, currency: "USD", retailerUrl: "https://www.maccosmetics.com", country: "USA" },
  { id: "us_003", name: "Pillow Talk Matte Revolution", brand: "Charlotte Tilbury", category: "lipstick", hexCode: "#D4907A", red: 212, green: 144, blue: 122, colorName: "Soft Nude Pink", price: 34, currency: "USD", retailerUrl: "https://www.charlottetilbury.com", country: "USA" },
  { id: "us_004", name: "Soft Stretch Concealer", brand: "NARS", category: "foundation", hexCode: "#E8C8A0", red: 232, green: 200, blue: 160, colorName: "Light Warm", price: 30, currency: "USD", retailerUrl: "https://www.narscosmetics.com", country: "USA" },
  { id: "us_005", name: "Orgasm Blush", brand: "NARS", category: "blush", hexCode: "#E8907A", red: 232, green: 144, blue: 122, colorName: "Peachy Pink Shimmer", price: 32, currency: "USD", retailerUrl: "https://www.narscosmetics.com", country: "USA" },
  { id: "us_006", name: "Pro Filt'r Foundation 120W", brand: "Fenty Beauty", category: "foundation", hexCode: "#E8C8A0", red: 232, green: 200, blue: 160, colorName: "Light Warm", price: 38, currency: "USD", retailerUrl: "https://www.fentybeauty.com", country: "USA" },
  { id: "us_007", name: "Pro Filt'r Foundation 445W", brand: "Fenty Beauty", category: "foundation", hexCode: "#8B5E3C", red: 139, green: 94, blue: 60, colorName: "Deep Warm", price: 38, currency: "USD", retailerUrl: "https://www.fentybeauty.com", country: "USA" },
  { id: "us_008", name: "Better Than Sex Mascara", brand: "Too Faced", category: "mascara", hexCode: "#1A1A1A", red: 26, green: 26, blue: 26, colorName: "Jet Black", price: 27, currency: "USD", retailerUrl: "https://www.toofaced.com", country: "USA" },
  { id: "us_009", name: "Lash Sensational Mascara", brand: "Maybelline", category: "mascara", hexCode: "#0D0D0D", red: 13, green: 13, blue: 13, colorName: "Blackest Black", price: 10, currency: "USD", retailerUrl: "https://www.maybelline.com", country: "USA" },
  { id: "us_010", name: "Wicked Precise Lip Liner - Red", brand: "e.l.f.", category: "lip_liner", hexCode: "#C0192B", red: 192, green: 25, blue: 43, colorName: "Classic Red", price: 4, currency: "USD", retailerUrl: "https://www.elfcosmetics.com", country: "USA" },
  { id: "us_011", name: "Butter Gloss - Peach Cobbler", brand: "NYX", category: "lipstick", hexCode: "#E8A87A", red: 232, green: 168, blue: 122, colorName: "Warm Peach", price: 8, currency: "USD", retailerUrl: "https://www.nyxcosmetics.com", country: "USA" },
  { id: "us_012", name: "Fit Me Foundation 120", brand: "Maybelline", category: "foundation", hexCode: "#F0D8B8", red: 240, green: 216, blue: 184, colorName: "Classic Ivory", price: 10, currency: "USD", retailerUrl: "https://www.maybelline.com", country: "USA" },
  { id: "us_013", name: "Kalahari Sun Highlighter", brand: "Fenty Beauty", category: "highlighter", hexCode: "#FFD700", red: 255, green: 215, blue: 0, colorName: "Golden Glow", price: 38, currency: "USD", retailerUrl: "https://www.fentybeauty.com", country: "USA" },
  { id: "us_014", name: "Scandal'Eyes Mascara Black", brand: "Rimmel", category: "mascara", hexCode: "#111111", red: 17, green: 17, blue: 17, colorName: "Black", price: 9, currency: "USD", retailerUrl: "https://www.rimmellondon.com", country: "USA" },
  { id: "us_015", name: "Nano Brow Pencil - Brunette", brand: "e.l.f.", category: "eyeshadow", hexCode: "#6B4226", red: 107, green: 66, blue: 38, colorName: "Brunette", price: 10, currency: "USD", retailerUrl: "https://www.elfcosmetics.com", country: "USA" },
  { id: "us_016", name: "Longwear Nail Polish - Fishnet", brand: "OPI", category: "nail_polish", hexCode: "#C0192B", red: 192, green: 25, blue: 43, colorName: "Classic Red", price: 11, currency: "USD", retailerUrl: "https://www.opi.com", country: "USA" },
  { id: "us_017", name: "Nail Polish - Ballet Slippers", brand: "Essie", category: "nail_polish", hexCode: "#F2D0C8", red: 242, green: 208, blue: 200, colorName: "Sheer Pink", price: 9, currency: "USD", retailerUrl: "https://www.essie.com", country: "USA" },
  { id: "us_018", name: "Nail Polish - Bordeaux", brand: "Essie", category: "nail_polish", hexCode: "#6B1A2B", red: 107, green: 26, blue: 43, colorName: "Deep Burgundy", price: 9, currency: "USD", retailerUrl: "https://www.essie.com", country: "USA" },
  { id: "us_019", name: "Nail Polish - Malaga Wine", brand: "OPI", category: "nail_polish", hexCode: "#7B2D3A", red: 123, green: 45, blue: 58, colorName: "Wine Red", price: 11, currency: "USD", retailerUrl: "https://www.opi.com", country: "USA" },
  { id: "us_020", name: "Eyeshadow Palette - Naked", brand: "Urban Decay", category: "eyeshadow", hexCode: "#C4956A", red: 196, green: 149, blue: 106, colorName: "Neutral Tones", price: 54, currency: "USD", retailerUrl: "https://www.urbandecay.com", country: "USA" },

  // ── INDIA ────────────────────────────────────────────────────────────────
  { id: "in_001", name: "Absolute Argan Oil Lip Color - Dusty Rose", brand: "Lakme", category: "lipstick", hexCode: "#C07878", red: 192, green: 120, blue: 120, colorName: "Dusty Rose", price: 550, currency: "INR", retailerUrl: "https://www.nykaa.com/lakme", country: "India" },
  { id: "in_002", name: "9 to 5 Primer + Matte - Blushing Nude", brand: "Lakme", category: "lipstick", hexCode: "#D4A090", red: 212, green: 160, blue: 144, colorName: "Blushing Nude", price: 399, currency: "INR", retailerUrl: "https://www.nykaa.com/lakme", country: "India" },
  { id: "in_003", name: "Matte As Hell - Scarlett O'Hara", brand: "Sugar Cosmetics", category: "lipstick", hexCode: "#C0303A", red: 192, green: 48, blue: 58, colorName: "Deep Scarlet", price: 499, currency: "INR", retailerUrl: "https://www.nykaa.com/sugar", country: "India" },
  { id: "in_004", name: "So Matte! - Mauve Mischief", brand: "Nykaa Cosmetics", category: "lipstick", hexCode: "#B07890", red: 176, green: 120, blue: 144, colorName: "Mauve Pink", price: 349, currency: "INR", retailerUrl: "https://www.nykaa.com", country: "India" },
  { id: "in_005", name: "Velvet Matte - Peach Temptation", brand: "Colorbar", category: "lipstick", hexCode: "#E8A07A", red: 232, green: 160, blue: 122, colorName: "Warm Peach", price: 425, currency: "INR", retailerUrl: "https://www.nykaa.com/colorbar", country: "India" },
  { id: "in_006", name: "Fit Me Foundation 128", brand: "Maybelline", category: "foundation", hexCode: "#D4A882", red: 212, green: 168, blue: 130, colorName: "Warm Nude", price: 299, currency: "INR", retailerUrl: "https://www.nykaa.com/maybelline", country: "India" },
  { id: "in_007", name: "HD Blush - Peach Blossom", brand: "Faces Canada", category: "blush", hexCode: "#F0A890", red: 240, green: 168, blue: 144, colorName: "Peach Blossom", price: 595, currency: "INR", retailerUrl: "https://www.nykaa.com/faces-canada", country: "India" },
  { id: "in_008", name: "Insta Glam Eyeshadow - Rose Gold", brand: "Lakme", category: "eyeshadow", hexCode: "#C8906A", red: 200, green: 144, blue: 106, colorName: "Rose Gold", price: 425, currency: "INR", retailerUrl: "https://www.nykaa.com/lakme", country: "India" },
  { id: "in_009", name: "Color Icon Eyeshadow - Walking On Eggshells", brand: "Wet n Wild", category: "eyeshadow", hexCode: "#D4B896", red: 212, green: 184, blue: 150, colorName: "Nude Neutrals", price: 299, currency: "INR", retailerUrl: "https://www.nykaa.com", country: "India" },
  { id: "in_010", name: "Nail Enamel - Fuschia", brand: "Lakme", category: "nail_polish", hexCode: "#E8407A", red: 232, green: 64, blue: 122, colorName: "Fuchsia Pink", price: 99, currency: "INR", retailerUrl: "https://www.nykaa.com/lakme", country: "India" },
  { id: "in_011", name: "Nail Enamel - Brick Red", brand: "Lakme", category: "nail_polish", hexCode: "#A0302A", red: 160, green: 48, blue: 42, colorName: "Brick Red", price: 99, currency: "INR", retailerUrl: "https://www.nykaa.com/lakme", country: "India" },
  { id: "in_012", name: "Volume Express Mascara", brand: "Maybelline", category: "mascara", hexCode: "#0D0D0D", red: 13, green: 13, blue: 13, colorName: "Blackest Black", price: 299, currency: "INR", retailerUrl: "https://www.nykaa.com/maybelline", country: "India" },
  { id: "in_013", name: "Colossal Kajal", brand: "Maybelline", category: "mascara", hexCode: "#111111", red: 17, green: 17, blue: 17, colorName: "Black", price: 149, currency: "INR", retailerUrl: "https://www.nykaa.com/maybelline", country: "India" },
  { id: "in_014", name: "Matte Lip Liner - Red", brand: "Sugar Cosmetics", category: "lip_liner", hexCode: "#C0192B", red: 192, green: 25, blue: 43, colorName: "Classic Red", price: 349, currency: "INR", retailerUrl: "https://www.nykaa.com/sugar", country: "India" },
  { id: "in_015", name: "Foundation Stick - Ivory", brand: "Colorbar", category: "foundation", hexCode: "#F0D8C0", red: 240, green: 216, blue: 192, colorName: "Ivory", price: 899, currency: "INR", retailerUrl: "https://www.nykaa.com/colorbar", country: "India" },
  { id: "in_016", name: "Highlighter - Champagne", brand: "Nykaa Cosmetics", category: "highlighter", hexCode: "#F5E6C8", red: 245, green: 230, blue: 200, colorName: "Champagne", price: 599, currency: "INR", retailerUrl: "https://www.nykaa.com", country: "India" },

  // ── CHINA ────────────────────────────────────────────────────────────────
  { id: "cn_001", name: "Blooming Rouge Lipstick - 01 Classic Red", brand: "Florasis 花西子", category: "lipstick", hexCode: "#C0392B", red: 192, green: 57, blue: 43, colorName: "Classic Red", price: 148, currency: "CNY", retailerUrl: "https://shop.florasis.com", country: "China" },
  { id: "cn_002", name: "Blooming Rouge Lipstick - 06 Soft Rose", brand: "Florasis 花西子", category: "lipstick", hexCode: "#E8768A", red: 232, green: 118, blue: 138, colorName: "Soft Rose Pink", price: 148, currency: "CNY", retailerUrl: "https://shop.florasis.com", country: "China" },
  { id: "cn_003", name: "Blooming Rouge Lipstick - 11 Coral", brand: "Florasis 花西子", category: "lipstick", hexCode: "#D95B43", red: 217, green: 91, blue: 67, colorName: "Vermilion Coral", price: 148, currency: "CNY", retailerUrl: "https://shop.florasis.com", country: "China" },
  { id: "cn_004", name: "Embroidered Blush - 01 Peach Blossom", brand: "Florasis 花西子", category: "blush", hexCode: "#F2A0A8", red: 242, green: 160, blue: 168, colorName: "Peach Blossom Pink", price: 188, currency: "CNY", retailerUrl: "https://shop.florasis.com", country: "China" },
  { id: "cn_005", name: "Floral Nail Polish - 03 Deep Crimson", brand: "Florasis 花西子", category: "nail_polish", hexCode: "#A93226", red: 169, green: 50, blue: 38, colorName: "Deep Crimson", price: 88, currency: "CNY", retailerUrl: "https://shop.florasis.com", country: "China" },
  { id: "cn_006", name: "Floral Nail Polish - 07 Coral Pink", brand: "Florasis 花西子", category: "nail_polish", hexCode: "#F07868", red: 240, green: 120, blue: 104, colorName: "Coral Pink", price: 88, currency: "CNY", retailerUrl: "https://shop.florasis.com", country: "China" },
  { id: "cn_007", name: "Explorer Lipstick - 02 Warm Nude", brand: "Perfect Diary 完美日记", category: "lipstick", hexCode: "#E8A0A8", red: 232, green: 160, blue: 168, colorName: "Warm Nude Pink", price: 59, currency: "CNY", retailerUrl: "https://www.perfectdiary.com", country: "China" },
  { id: "cn_008", name: "Explorer Lipstick - 07 Dusty Mauve", brand: "Perfect Diary 完美日记", category: "lipstick", hexCode: "#C17B7B", red: 193, green: 123, blue: 123, colorName: "Dusty Mauve Rose", price: 59, currency: "CNY", retailerUrl: "https://www.perfectdiary.com", country: "China" },
  { id: "cn_009", name: "Wildly Blooming Eyeshadow Palette", brand: "Perfect Diary 完美日记", category: "eyeshadow", hexCode: "#C4A882", red: 196, green: 168, blue: 130, colorName: "Warm Terracotta Mix", price: 129, currency: "CNY", retailerUrl: "https://www.perfectdiary.com", country: "China" },
  { id: "cn_010", name: "Silky Blush - 03 Apricot", brand: "Perfect Diary 完美日记", category: "blush", hexCode: "#F0B89A", red: 240, green: 184, blue: 154, colorName: "Warm Apricot", price: 69, currency: "CNY", retailerUrl: "https://www.perfectdiary.com", country: "China" },
  { id: "cn_011", name: "Watery Lip Glaze - 33 Cherry Red", brand: "Judydoll 橘朵", category: "lipstick", hexCode: "#E05B6E", red: 224, green: 91, blue: 110, colorName: "Bright Cherry Red", price: 39, currency: "CNY", retailerUrl: "https://www.judydoll.com", country: "China" },
  { id: "cn_012", name: "Watery Lip Glaze - 08 Rose Petal", brand: "Judydoll 橘朵", category: "lipstick", hexCode: "#E891A8", red: 232, green: 145, blue: 168, colorName: "Rose Petal Pink", price: 39, currency: "CNY", retailerUrl: "https://www.judydoll.com", country: "China" },
  { id: "cn_013", name: "Jelly Nail Polish - 11 Coral Orange", brand: "Judydoll 橘朵", category: "nail_polish", hexCode: "#F07850", red: 240, green: 120, blue: 80, colorName: "Coral Orange", price: 29, currency: "CNY", retailerUrl: "https://www.judydoll.com", country: "China" },
  { id: "cn_014", name: "Flawless Foundation - N20 Ivory", brand: "Maogeping 毛戈平", category: "foundation", hexCode: "#F0D8C0", red: 240, green: 216, blue: 192, colorName: "Light Ivory", price: 380, currency: "CNY", retailerUrl: "https://www.maogeping.com", country: "China" },
  { id: "cn_015", name: "Flawless Foundation - N40 Natural Beige", brand: "Maogeping 毛戈平", category: "foundation", hexCode: "#D4A882", red: 212, green: 168, blue: 130, colorName: "Natural Beige", price: 380, currency: "CNY", retailerUrl: "https://www.maogeping.com", country: "China" },
  { id: "cn_016", name: "Sculpting Blush - 02 Rose Gold", brand: "Maogeping 毛戈平", category: "blush", hexCode: "#D4808A", red: 212, green: 128, blue: 138, colorName: "Rose Gold", price: 260, currency: "CNY", retailerUrl: "https://www.maogeping.com", country: "China" },
  { id: "cn_017", name: "Ruby Woo (Tmall China)", brand: "MAC", category: "lipstick", hexCode: "#BB1C2B", red: 187, green: 28, blue: 43, colorName: "True Red", price: 190, currency: "CNY", retailerUrl: "https://www.maccosmetics.com", country: "China" },
  { id: "cn_018", name: "Velvet Teddy (Tmall China)", brand: "MAC", category: "lipstick", hexCode: "#B07060", red: 176, green: 112, blue: 96, colorName: "Muted Beige Pink", price: 190, currency: "CNY", retailerUrl: "https://www.maccosmetics.com", country: "China" },
  { id: "cn_019", name: "L'Absolu Rouge 132 (Tmall)", brand: "Lancôme", category: "lipstick", hexCode: "#C0404A", red: 192, green: 64, blue: 74, colorName: "Deep Rose Red", price: 340, currency: "CNY", retailerUrl: "https://www.lancome.com", country: "China" },
  { id: "cn_020", name: "Colorkey Lip Mud - Bean Paste", brand: "Colorkey 珂拉琪", category: "lipstick", hexCode: "#8B4A50", red: 139, green: 74, blue: 80, colorName: "Bean Paste", price: 69, currency: "CNY", retailerUrl: "https://www.colorkey.com.cn", country: "China" },
  { id: "cn_021", name: "Colorkey Air Lip Velvet - Coral", brand: "Colorkey 珂拉琪", category: "lipstick", hexCode: "#E87060", red: 232, green: 112, blue: 96, colorName: "Warm Coral", price: 69, currency: "CNY", retailerUrl: "https://www.colorkey.com.cn", country: "China" },
  { id: "cn_022", name: "Mascara - Long & Curling Black", brand: "Perfect Diary 完美日记", category: "mascara", hexCode: "#111111", red: 17, green: 17, blue: 17, colorName: "Black", price: 79, currency: "CNY", retailerUrl: "https://www.perfectdiary.com", country: "China" },
  { id: "cn_023", name: "Highlighter Palette - Aurora", brand: "Florasis 花西子", category: "highlighter", hexCode: "#F8E8D8", red: 248, green: 232, blue: 216, colorName: "Pearl Aurora", price: 228, currency: "CNY", retailerUrl: "https://shop.florasis.com", country: "China" },

  // ── BRAZIL ───────────────────────────────────────────────────────────────
  { id: "br_001", name: "Batom Matte - 311 Terracota", brand: "O Boticário", category: "lipstick", hexCode: "#C07050", red: 192, green: 112, blue: 80, colorName: "Terracotta", price: 39.9, currency: "BRL", retailerUrl: "https://www.boticario.com.br", country: "Brazil" },
  { id: "br_002", name: "Batom Cremoso - Vermelho Intenso", brand: "Natura", category: "lipstick", hexCode: "#B02030", red: 176, green: 32, blue: 48, colorName: "Intense Red", price: 34.9, currency: "BRL", retailerUrl: "https://www.natura.com.br", country: "Brazil" },
  { id: "br_003", name: "Batom Matte - 14 Nude Rosado", brand: "Vult", category: "lipstick", hexCode: "#D4987A", red: 212, green: 152, blue: 122, colorName: "Rosy Nude", price: 14.9, currency: "BRL", retailerUrl: "https://www.google.com/search?q=Vult+cosmetics+buy+Brazil", country: "Brazil" },
  { id: "br_004", name: "Batom Matte - 12 Roxo Uva", brand: "Dailus", category: "lipstick", hexCode: "#8B3A6A", red: 139, green: 58, blue: 106, colorName: "Plum Purple", price: 12.9, currency: "BRL", retailerUrl: "https://www.dailus.com.br", country: "Brazil" },
  { id: "br_005", name: "Base Líquida - B10 Claro Frio", brand: "O Boticário", category: "foundation", hexCode: "#F0D8C0", red: 240, green: 216, blue: 192, colorName: "Light Cool", price: 79.9, currency: "BRL", retailerUrl: "https://www.boticario.com.br", country: "Brazil" },
  { id: "br_006", name: "Blush Duo - Pêssego & Dourado", brand: "O Boticário", category: "blush", hexCode: "#F0B890", red: 240, green: 184, blue: 144, colorName: "Peach & Gold", price: 59.9, currency: "BRL", retailerUrl: "https://www.boticario.com.br", country: "Brazil" },
  { id: "br_007", name: "Esmalte - Vermelho Clássico", brand: "Risqué", category: "nail_polish", hexCode: "#C0192B", red: 192, green: 25, blue: 43, colorName: "Classic Red", price: 8.9, currency: "BRL", retailerUrl: "https://www.risque.com.br", country: "Brazil" },
  { id: "br_008", name: "Esmalte - Rosa Ballet", brand: "Risqué", category: "nail_polish", hexCode: "#F2D0C8", red: 242, green: 208, blue: 200, colorName: "Ballet Pink", price: 8.9, currency: "BRL", retailerUrl: "https://www.risque.com.br", country: "Brazil" },
  { id: "br_009", name: "Esmalte - Borgonha", brand: "Colorama", category: "nail_polish", hexCode: "#6B1A2B", red: 107, green: 26, blue: 43, colorName: "Burgundy", price: 6.9, currency: "BRL", retailerUrl: "https://www.colorama.com.br", country: "Brazil" },
  { id: "br_010", name: "Mascara Volume - Preta", brand: "Vult", category: "mascara", hexCode: "#111111", red: 17, green: 17, blue: 17, colorName: "Black", price: 19.9, currency: "BRL", retailerUrl: "https://www.google.com/search?q=Vult+cosmetics+buy+Brazil", country: "Brazil" },
  { id: "br_011", name: "Delineador Líquido Preto", brand: "Dailus", category: "mascara", hexCode: "#0D0D0D", red: 13, green: 13, blue: 13, colorName: "Jet Black", price: 14.9, currency: "BRL", retailerUrl: "https://www.dailus.com.br", country: "Brazil" },
  { id: "br_012", name: "Paleta de Sombras - Rosê", brand: "Vult", category: "eyeshadow", hexCode: "#D49090", red: 212, green: 144, blue: 144, colorName: "Rose Tones", price: 34.9, currency: "BRL", retailerUrl: "https://www.google.com/search?q=Vult+cosmetics+buy+Brazil", country: "Brazil" },
  { id: "br_013", name: "Iluminador - Dourado", brand: "Natura", category: "highlighter", hexCode: "#F5D06A", red: 245, green: 208, blue: 106, colorName: "Gold", price: 49.9, currency: "BRL", retailerUrl: "https://www.natura.com.br", country: "Brazil" },
  { id: "br_014", name: "Batom Gloss - Coral", brand: "Avon", category: "lipstick", hexCode: "#E87060", red: 232, green: 112, blue: 96, colorName: "Coral", price: 24.9, currency: "BRL", retailerUrl: "https://www.avon.com.br", country: "Brazil" },

  // ── INDONESIA ────────────────────────────────────────────────────────────
  { id: "id_001", name: "Exclusive Matte Lip Cream - 22 Rosy Mauve", brand: "Wardah", category: "lipstick", hexCode: "#C08090", red: 192, green: 128, blue: 144, colorName: "Rosy Mauve", price: 55000, currency: "IDR", retailerUrl: "https://www.wardahbeauty.com", country: "Indonesia" },
  { id: "id_002", name: "Exclusive Matte Lip Cream - 08 Brick Red", brand: "Wardah", category: "lipstick", hexCode: "#A03028", red: 160, green: 48, blue: 40, colorName: "Brick Red", price: 55000, currency: "IDR", retailerUrl: "https://www.wardahbeauty.com", country: "Indonesia" },
  { id: "id_003", name: "Creamatte Lipstick - 08 Brick Lane", brand: "Emina", category: "lipstick", hexCode: "#B05840", red: 176, green: 88, blue: 64, colorName: "Burnt Brick", price: 32000, currency: "IDR", retailerUrl: "https://www.eminacosmetics.com", country: "Indonesia" },
  { id: "id_004", name: "Blur & Glow Cushion - 21N Natural Beige", brand: "Somethinc", category: "foundation", hexCode: "#D4A882", red: 212, green: 168, blue: 130, colorName: "Natural Beige", price: 178000, currency: "IDR", retailerUrl: "https://www.somethinc.com", country: "Indonesia" },
  { id: "id_005", name: "Powerstay Lip Cream - 016 Darling", brand: "Make Over", category: "lipstick", hexCode: "#C87870", red: 200, green: 120, blue: 112, colorName: "Muted Rose", price: 95000, currency: "IDR", retailerUrl: "https://www.makeovercosmetics.com", country: "Indonesia" },
  { id: "id_006", name: "The One Eyeshadow - 02 Rose", brand: "Y.O.U", category: "eyeshadow", hexCode: "#D49090", red: 212, green: 144, blue: 144, colorName: "Rose Tones", price: 89000, currency: "IDR", retailerUrl: "https://www.youbeauty.co.id", country: "Indonesia" },
  { id: "id_007", name: "Nail Polish - Dusty Pink", brand: "Wardah", category: "nail_polish", hexCode: "#E8B0B8", red: 232, green: 176, blue: 184, colorName: "Dusty Pink", price: 25000, currency: "IDR", retailerUrl: "https://www.wardahbeauty.com", country: "Indonesia" },
  { id: "id_008", name: "Nail Polish - Red Velvet", brand: "Emina", category: "nail_polish", hexCode: "#9B1B30", red: 155, green: 27, blue: 48, colorName: "Red Velvet", price: 20000, currency: "IDR", retailerUrl: "https://www.eminacosmetics.com", country: "Indonesia" },
  { id: "id_009", name: "Mascara - Big Eyes Black", brand: "Wardah", category: "mascara", hexCode: "#111111", red: 17, green: 17, blue: 17, colorName: "Black", price: 45000, currency: "IDR", retailerUrl: "https://www.wardahbeauty.com", country: "Indonesia" },
  { id: "id_010", name: "Blush On - 02 Peach Glow", brand: "Wardah", category: "blush", hexCode: "#F0A890", red: 240, green: 168, blue: 144, colorName: "Peach Glow", price: 65000, currency: "IDR", retailerUrl: "https://www.wardahbeauty.com", country: "Indonesia" },
  { id: "id_011", name: "Highlighter - Gold Beam", brand: "Make Over", category: "highlighter", hexCode: "#F5D06A", red: 245, green: 208, blue: 106, colorName: "Gold Beam", price: 120000, currency: "IDR", retailerUrl: "https://www.makeovercosmetics.com", country: "Indonesia" },
  { id: "id_012", name: "Lip Liner - Nude Pink", brand: "Somethinc", category: "lip_liner", hexCode: "#D4908A", red: 212, green: 144, blue: 138, colorName: "Nude Pink", price: 85000, currency: "IDR", retailerUrl: "https://www.somethinc.com", country: "Indonesia" },

  // ── NIGERIA ──────────────────────────────────────────────────────────────
  { id: "ng_001", name: "Lip Gloss - Fuchsia", brand: "Zaron", category: "lipstick", hexCode: "#E0407A", red: 224, green: 64, blue: 122, colorName: "Fuchsia", price: 3500, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },
  { id: "ng_002", name: "Lip Colour - Chocolate Berry", brand: "House of Tara", category: "lipstick", hexCode: "#7B3040", red: 123, green: 48, blue: 64, colorName: "Chocolate Berry", price: 2800, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },
  { id: "ng_003", name: "Foundation Stick - Caramel 06", brand: "Zaron", category: "foundation", hexCode: "#A87050", red: 168, green: 112, blue: 80, colorName: "Caramel", price: 4200, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },
  { id: "ng_004", name: "Matte Lipstick - Solange", brand: "Hegai & Esther", category: "lipstick", hexCode: "#9B3050", red: 155, green: 48, blue: 80, colorName: "Deep Berry", price: 3200, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },
  { id: "ng_005", name: "Blush - Cocoa Rose", brand: "Zaron", category: "blush", hexCode: "#C08070", red: 192, green: 128, blue: 112, colorName: "Cocoa Rose", price: 3000, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },
  { id: "ng_006", name: "Nail Polish - Nude Beige", brand: "Zaron", category: "nail_polish", hexCode: "#D4B090", red: 212, green: 176, blue: 144, colorName: "Nude Beige", price: 1500, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },
  { id: "ng_007", name: "Nail Polish - Wine Red", brand: "House of Tara", category: "nail_polish", hexCode: "#7B2030", red: 123, green: 32, blue: 48, colorName: "Wine Red", price: 1800, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },
  { id: "ng_008", name: "Mascara - Black Volume", brand: "Zaron", category: "mascara", hexCode: "#111111", red: 17, green: 17, blue: 17, colorName: "Black", price: 2500, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },
  { id: "ng_009", name: "Eyeshadow Palette - Earth Tones", brand: "House of Tara", category: "eyeshadow", hexCode: "#A07050", red: 160, green: 112, blue: 80, colorName: "Earth Tones", price: 4500, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },
  { id: "ng_010", name: "Highlighter - Bronze Glow", brand: "Zaron", category: "highlighter", hexCode: "#C87840", red: 200, green: 120, blue: 64, colorName: "Bronze Glow", price: 3800, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },
  { id: "ng_011", name: "Foundation - Ebony 08", brand: "Zaron", category: "foundation", hexCode: "#4A2818", red: 74, green: 40, blue: 24, colorName: "Deep Ebony", price: 5500, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },
  { id: "ng_012", name: "Lip Liner - Deep Brown", brand: "Hegai & Esther", category: "lip_liner", hexCode: "#6B3828", red: 107, green: 56, blue: 40, colorName: "Deep Brown", price: 1500, currency: "NGN", retailerUrl: "https://www.jumia.com.ng", country: "Nigeria" },

  // ── PREMIUM USA ──────────────────────────────────────────────────────────
  { id: "us_p01", name: "Soft Pinch Liquid Blush - Joy", brand: "Rare Beauty", category: "blush", hexCode: "#E87B8A", red: 232, green: 123, blue: 138, colorName: "Warm Pink", price: 23, currency: "USD", retailerUrl: "https://www.rarebeauty.com", country: "USA" },
  { id: "us_p02", name: "Soft Pinch Liquid Blush - Bliss", brand: "Rare Beauty", category: "blush", hexCode: "#C96B70", red: 201, green: 107, blue: 112, colorName: "Berry Mauve", price: 23, currency: "USD", retailerUrl: "https://www.rarebeauty.com", country: "USA" },
  { id: "us_p03", name: "Cloud Paint - Dusk", brand: "Glossier", category: "blush", hexCode: "#D4907A", red: 212, green: 144, blue: 122, colorName: "Warm Rose", price: 20, currency: "USD", retailerUrl: "https://www.glossier.com", country: "USA" },
  { id: "us_p04", name: "Cloud Paint - Storm", brand: "Glossier", category: "blush", hexCode: "#B85C5C", red: 184, green: 92, blue: 92, colorName: "Deep Berry", price: 20, currency: "USD", retailerUrl: "https://www.glossier.com", country: "USA" },
  { id: "us_p05", name: "Revealer Concealer - 3W", brand: "Kosas", category: "foundation", hexCode: "#E8C8A0", red: 232, green: 200, blue: 160, colorName: "Light Warm", price: 28, currency: "USD", retailerUrl: "https://www.kosas.com", country: "USA" },
  { id: "us_p06", name: "Glowy Super Gel - Starglow", brand: "Saie", category: "highlighter", hexCode: "#F5D5C8", red: 245, green: 213, blue: 200, colorName: "Champagne Glow", price: 25, currency: "USD", retailerUrl: "https://www.saiehello.com", country: "USA" },
  { id: "us_p07", name: "BeachPlease Lip + Cheek - Golden Hour", brand: "Tower 28", category: "blush", hexCode: "#E8A87A", red: 232, green: 168, blue: 122, colorName: "Warm Peach", price: 20, currency: "USD", retailerUrl: "https://www.tower28beauty.com", country: "USA" },
  { id: "us_p08", name: "Naked3 Eyeshadow Palette", brand: "Urban Decay", category: "eyeshadow", hexCode: "#D4A8B0", red: 212, green: 168, blue: 176, colorName: "Rose Neutrals", price: 54, currency: "USD", retailerUrl: "https://www.urbandecay.com", country: "USA" },
  { id: "us_p09", name: "Lip Injection Maximum Plump - Pink", brand: "Too Faced", category: "lipstick", hexCode: "#E88898", red: 232, green: 136, blue: 152, colorName: "Bubblegum Pink", price: 29, currency: "USD", retailerUrl: "https://www.toofaced.com", country: "USA" },
  { id: "us_p10", name: "Maracuja Juicy Lip - Orchid", brand: "Tarte", category: "lipstick", hexCode: "#C87088", red: 200, green: 112, blue: 136, colorName: "Rosy Orchid", price: 21, currency: "USD", retailerUrl: "https://www.tartecosmetics.com", country: "USA" },

  // ── PREMIUM INDIA ────────────────────────────────────────────────────────
  { id: "in_p01", name: "Matte As Hell Crayon - Viola", brand: "Sugar Cosmetics", category: "lipstick", hexCode: "#8B3A62", red: 139, green: 58, blue: 98, colorName: "Deep Plum", price: 799, currency: "INR", retailerUrl: "https://www.sugarcosmetics.com", country: "India" },
  { id: "in_p02", name: "Air Kiss Moisturizing Lipstick - Cherry", brand: "Sugar Cosmetics", category: "lipstick", hexCode: "#C8384A", red: 200, green: 56, blue: 74, colorName: "Cherry Red", price: 699, currency: "INR", retailerUrl: "https://www.sugarcosmetics.com", country: "India" },
  { id: "in_p03", name: "Velvet Matte Lipstick - Peach Crush", brand: "Colorbar", category: "lipstick", hexCode: "#E8A090", red: 232, green: 160, blue: 144, colorName: "Warm Peach", price: 450, currency: "INR", retailerUrl: "https://www.colorbarcosmetics.com", country: "India" },
  { id: "in_p04", name: "Matte In Heaven Lipstick - Rose", brand: "Plum", category: "lipstick", hexCode: "#C07888", red: 192, green: 120, blue: 136, colorName: "Dusty Rose", price: 425, currency: "INR", retailerUrl: "https://www.plumgoodness.com", country: "India" },
  { id: "in_p05", name: "Eyes On Me! Eyeshadow - Bronze", brand: "Nykaa Cosmetics", category: "eyeshadow", hexCode: "#B08050", red: 176, green: 128, blue: 80, colorName: "Warm Bronze", price: 550, currency: "INR", retailerUrl: "https://www.nykaa.com", country: "India" },
  { id: "in_p06", name: "Skin Genius Foundation - 03 Warm", brand: "Nykaa Cosmetics", category: "foundation", hexCode: "#D8B890", red: 216, green: 184, blue: 144, colorName: "Medium Warm", price: 650, currency: "INR", retailerUrl: "https://www.nykaa.com", country: "India" },
  { id: "in_p07", name: "Blush Me! - Coral Sunset", brand: "Sugar Cosmetics", category: "blush", hexCode: "#E89078", red: 232, green: 144, blue: 120, colorName: "Coral Sunset", price: 599, currency: "INR", retailerUrl: "https://www.sugarcosmetics.com", country: "India" },
  { id: "in_p08", name: "Nail Polish - Berry Wine", brand: "Colorbar", category: "nail_polish", hexCode: "#7B2040", red: 123, green: 32, blue: 64, colorName: "Berry Wine", price: 225, currency: "INR", retailerUrl: "https://www.colorbarcosmetics.com", country: "India" },

  // ── PREMIUM BRAZIL ───────────────────────────────────────────────────────
  { id: "br_p01", name: "Una Artistry Batom - Vermelho", brand: "Natura", category: "lipstick", hexCode: "#C8282A", red: 200, green: 40, blue: 42, colorName: "True Red", price: 52, currency: "BRL", retailerUrl: "https://www.natura.com.br", country: "Brazil" },
  { id: "br_p02", name: "Make B. Lipstick - Nude Rose", brand: "O Boticário", category: "lipstick", hexCode: "#D4A098", red: 212, green: 160, blue: 152, colorName: "Nude Rose", price: 48, currency: "BRL", retailerUrl: "https://www.boticario.com.br", country: "Brazil" },
  { id: "br_p03", name: "Batom Líquido Matte - Marsala", brand: "Ruby Rose", category: "lipstick", hexCode: "#8B3A42", red: 139, green: 58, blue: 66, colorName: "Marsala", price: 18, currency: "BRL", retailerUrl: "https://www.rubyrose.com.br", country: "Brazil" },
  { id: "br_p04", name: "Batom Cremoso - Pêssego", brand: "Quem Disse Berenice", category: "lipstick", hexCode: "#E8A888", red: 232, green: 168, blue: 136, colorName: "Peach", price: 35, currency: "BRL", retailerUrl: "https://www.quemdisseberenice.com.br", country: "Brazil" },
  { id: "br_p05", name: "Blush Compacto - Coral", brand: "Natura", category: "blush", hexCode: "#E88870", red: 232, green: 136, blue: 112, colorName: "Coral", price: 45, currency: "BRL", retailerUrl: "https://www.natura.com.br", country: "Brazil" },
  { id: "br_p06", name: "Nativa SPA Foundation - 02", brand: "O Boticário", category: "foundation", hexCode: "#E0C8A8", red: 224, green: 200, blue: 168, colorName: "Light Medium", price: 68, currency: "BRL", retailerUrl: "https://www.boticario.com.br", country: "Brazil" },
  { id: "br_p07", name: "Paleta Sombras - Sunset", brand: "Ruby Rose", category: "eyeshadow", hexCode: "#C88060", red: 200, green: 128, blue: 96, colorName: "Warm Sunset", price: 25, currency: "BRL", retailerUrl: "https://www.rubyrose.com.br", country: "Brazil" },
  { id: "br_p08", name: "Esmalte - Rosa Chic", brand: "Natura", category: "nail_polish", hexCode: "#E8A0B0", red: 232, green: 160, blue: 176, colorName: "Chic Pink", price: 15, currency: "BRL", retailerUrl: "https://www.natura.com.br", country: "Brazil" },

  // ── PREMIUM CHINA ────────────────────────────────────────────────────────
  { id: "cn_p01", name: "Explorer Eyeshadow Palette - Amber", brand: "Perfect Diary", category: "eyeshadow", hexCode: "#C89060", red: 200, green: 144, blue: 96, colorName: "Amber Gold", price: 89, currency: "CNY", retailerUrl: "https://www.perfectdiary.com", country: "China" },
  { id: "cn_p02", name: "Rouge Lipstick - 202 Velvet Rose", brand: "Perfect Diary", category: "lipstick", hexCode: "#B85060", red: 184, green: 80, blue: 96, colorName: "Velvet Rose", price: 79, currency: "CNY", retailerUrl: "https://www.perfectdiary.com", country: "China" },
  { id: "cn_p03", name: "Blooming Rouge - M315 Peony", brand: "Florasis", category: "lipstick", hexCode: "#D87080", red: 216, green: 112, blue: 128, colorName: "Peony Pink", price: 219, currency: "CNY", retailerUrl: "https://www.florasis.com", country: "China" },
  { id: "cn_p04", name: "Floral Engraved Lipstick - Plum", brand: "Florasis", category: "lipstick", hexCode: "#9B3858", red: 155, green: 56, blue: 88, colorName: "Chinese Plum", price: 199, currency: "CNY", retailerUrl: "https://www.florasis.com", country: "China" },
  { id: "cn_p05", name: "Silky Blush - 03 Apricot", brand: "Judydoll", category: "blush", hexCode: "#E8A890", red: 232, green: 168, blue: 144, colorName: "Soft Apricot", price: 49, currency: "CNY", retailerUrl: "https://www.judydoll.com", country: "China" },
  { id: "cn_p06", name: "Liquid Lipstick - Maple Brown", brand: "Judydoll", category: "lipstick", hexCode: "#A06048", red: 160, green: 96, blue: 72, colorName: "Maple Brown", price: 45, currency: "CNY", retailerUrl: "https://www.judydoll.com", country: "China" },
  { id: "cn_p07", name: "Setting Powder - Translucent", brand: "Perfect Diary", category: "foundation", hexCode: "#F0E8D8", red: 240, green: 232, blue: 216, colorName: "Translucent", price: 69, currency: "CNY", retailerUrl: "https://www.perfectdiary.com", country: "China" },
  { id: "cn_p08", name: "Highlighter - Moonlight", brand: "Florasis", category: "highlighter", hexCode: "#F5E0D0", red: 245, green: 224, blue: 208, colorName: "Moonlight Glow", price: 169, currency: "CNY", retailerUrl: "https://www.florasis.com", country: "China" },

  // ── PREMIUM INDONESIA ────────────────────────────────────────────────────
  { id: "id_p01", name: "Exclusive Matte Lip Cream - 03 See You Latte", brand: "Wardah", category: "lipstick", hexCode: "#C89880", red: 200, green: 152, blue: 128, colorName: "Warm Latte", price: 55000, currency: "IDR", retailerUrl: "https://www.wardahbeauty.com", country: "Indonesia" },
  { id: "id_p02", name: "Exclusive Matte Lip Cream - 08 Pinky Plum", brand: "Wardah", category: "lipstick", hexCode: "#B86878", red: 184, green: 104, blue: 120, colorName: "Pinky Plum", price: 55000, currency: "IDR", retailerUrl: "https://www.wardahbeauty.com", country: "Indonesia" },
  { id: "id_p03", name: "Creamy Tint - Beet Bites", brand: "Emina", category: "lipstick", hexCode: "#C84858", red: 200, green: 72, blue: 88, colorName: "Beetroot Red", price: 33000, currency: "IDR", retailerUrl: "https://www.eminacosmetics.com", country: "Indonesia" },
  { id: "id_p04", name: "Powerstay Matte Lip Cream - 306", brand: "Make Over", category: "lipstick", hexCode: "#983848", red: 152, green: 56, blue: 72, colorName: "Deep Rose", price: 89000, currency: "IDR", retailerUrl: "https://www.makeoverforall.com", country: "Indonesia" },
  { id: "id_p05", name: "Lip Coat - Lavender Cream", brand: "BLP Beauty", category: "lipstick", hexCode: "#C8A0B0", red: 200, green: 160, blue: 176, colorName: "Lavender Cream", price: 129000, currency: "IDR", retailerUrl: "https://www.blpbeauty.com", country: "Indonesia" },
  { id: "id_p06", name: "Instaperfect Blush - Peach", brand: "Wardah", category: "blush", hexCode: "#E8A890", red: 232, green: 168, blue: 144, colorName: "Soft Peach", price: 65000, currency: "IDR", retailerUrl: "https://www.wardahbeauty.com", country: "Indonesia" },
  { id: "id_p07", name: "BB Cream - Natural", brand: "Emina", category: "foundation", hexCode: "#E8D0B0", red: 232, green: 208, blue: 176, colorName: "Natural Beige", price: 29000, currency: "IDR", retailerUrl: "https://www.eminacosmetics.com", country: "Indonesia" },
  { id: "id_p08", name: "Powerstay Foundation - 03 Nude", brand: "Make Over", category: "foundation", hexCode: "#D8B890", red: 216, green: 184, blue: 144, colorName: "Medium Nude", price: 145000, currency: "IDR", retailerUrl: "https://www.makeoverforall.com", country: "Indonesia" },

  // ── PREMIUM NIGERIA ──────────────────────────────────────────────────────
  { id: "ng_p01", name: "Lipstick - Royale", brand: "Zaron Cosmetics", category: "lipstick", hexCode: "#881830", red: 136, green: 24, blue: 48, colorName: "Deep Royale", price: 4500, currency: "NGN", retailerUrl: "https://www.zaroncosmetics.com", country: "Nigeria" },
  { id: "ng_p02", name: "Liquid Lipstick - Cocoa", brand: "Zaron Cosmetics", category: "lipstick", hexCode: "#7B4030", red: 123, green: 64, blue: 48, colorName: "Rich Cocoa", price: 5000, currency: "NGN", retailerUrl: "https://www.zaroncosmetics.com", country: "Nigeria" },
  { id: "ng_p03", name: "Flawless Foundation - Caramel", brand: "House of Tara", category: "foundation", hexCode: "#A07850", red: 160, green: 120, blue: 80, colorName: "Caramel", price: 8500, currency: "NGN", retailerUrl: "https://www.houseoftara.com", country: "Nigeria" },
  { id: "ng_p04", name: "True Color Foundation - Nutmeg", brand: "Black Opal", category: "foundation", hexCode: "#8B6840", red: 139, green: 104, blue: 64, colorName: "Nutmeg", price: 7500, currency: "NGN", retailerUrl: "https://www.blackopalbeauty.com", country: "Nigeria" },
  { id: "ng_p05", name: "True Color Foundation - Au Chocolat", brand: "Black Opal", category: "foundation", hexCode: "#6B4828", red: 107, green: 72, blue: 40, colorName: "Au Chocolat", price: 7500, currency: "NGN", retailerUrl: "https://www.blackopalbeauty.com", country: "Nigeria" },
  { id: "ng_p06", name: "Blush - Sunset Bronze", brand: "House of Tara", category: "blush", hexCode: "#C88858", red: 200, green: 136, blue: 88, colorName: "Sunset Bronze", price: 5500, currency: "NGN", retailerUrl: "https://www.houseoftara.com", country: "Nigeria" },
  { id: "ng_p07", name: "Lip Gloss - Rosewood", brand: "Zaron Cosmetics", category: "lipstick", hexCode: "#B07068", red: 176, green: 112, blue: 104, colorName: "Rosewood", price: 3500, currency: "NGN", retailerUrl: "https://www.zaroncosmetics.com", country: "Nigeria" },
  { id: "ng_p08", name: "Highlighter - Golden Girl", brand: "Black Opal", category: "highlighter", hexCode: "#E8C890", red: 232, green: 200, blue: 144, colorName: "Golden Girl", price: 6500, currency: "NGN", retailerUrl: "https://www.blackopalbeauty.com", country: "Nigeria" },

  // ── NEW CATEGORY: FOUNDATION ────────────────────────────────────────────
  { id: "fn_001", name: "Pro Filt'r Foundation 140W", brand: "Fenty Beauty", category: "foundation", hexCode: "#C68642", red: 198, green: 134, blue: 66, colorName: "Medium Warm", price: 29, currency: "USD", retailerUrl: "https://www.google.com/search?q=Fenty+Beauty+Pro+Filtr+Foundation+140W+buy", country: "USA" },
  { id: "fn_002", name: "Pro Filt'r Foundation 385W", brand: "Fenty Beauty", category: "foundation", hexCode: "#8D5524", red: 141, green: 85, blue: 36, colorName: "Deep Warm", price: 29, currency: "USD", retailerUrl: "https://www.google.com/search?q=Fenty+Beauty+Pro+Filtr+Foundation+385W+buy", country: "USA" },
  { id: "fn_003", name: "Studio Fix Fluid NC15", brand: "MAC", category: "foundation", hexCode: "#F5CBA7", red: 245, green: 203, blue: 167, colorName: "Light Neutral Cool", price: 35, currency: "USD", retailerUrl: "https://www.google.com/search?q=MAC+Studio+Fix+Fluid+NC15+buy", country: "USA" },
  { id: "fn_004", name: "Studio Fix Fluid NW45", brand: "MAC", category: "foundation", hexCode: "#8B6914", red: 139, green: 105, blue: 20, colorName: "Deep Neutral Warm", price: 35, currency: "USD", retailerUrl: "https://www.google.com/search?q=MAC+Studio+Fix+Fluid+NW45+buy", country: "USA" },
  { id: "fn_005", name: "Fit Me 120 Classic Ivory", brand: "Maybelline", category: "foundation", hexCode: "#F5DEB3", red: 245, green: 222, blue: 179, colorName: "Classic Ivory", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Maybelline+Fit+Me+120+Classic+Ivory+buy", country: "USA" },
  { id: "fn_006", name: "Fit Me 330 Toffee", brand: "Maybelline", category: "foundation", hexCode: "#8B6914", red: 139, green: 105, blue: 20, colorName: "Toffee", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Maybelline+Fit+Me+330+Toffee+buy", country: "USA" },
  { id: "fn_007", name: "Natural Radiant Longwear Deauville", brand: "NARS", category: "foundation", hexCode: "#F5CBA7", red: 245, green: 203, blue: 167, colorName: "Light Warm", price: 49, currency: "USD", retailerUrl: "https://www.google.com/search?q=NARS+Natural+Radiant+Longwear+Deauville+buy", country: "USA" },
  { id: "fn_008", name: "True Match W2 Light Warm", brand: "L'Oreal", category: "foundation", hexCode: "#FDDBB4", red: 253, green: 219, blue: 180, colorName: "Light Warm", price: 12, currency: "USD", retailerUrl: "https://www.google.com/search?q=L%27Oreal+True+Match+W2+buy", country: "USA" },
  { id: "fn_009", name: "Perfecting Liquid Foundation Coral", brand: "Lakme", category: "foundation", hexCode: "#E8A87C", red: 232, green: 168, blue: 124, colorName: "Coral", price: 499, currency: "INR", retailerUrl: "https://www.google.com/search?q=Lakme+Perfecting+Liquid+Foundation+Coral+buy", country: "India" },
  { id: "fn_010", name: "SKINgenius Foundation Porcelain", brand: "Nykaa Cosmetics", category: "foundation", hexCode: "#F5E6D3", red: 245, green: 230, blue: 211, colorName: "Porcelain", price: 799, currency: "INR", retailerUrl: "https://www.google.com/search?q=Nykaa+SKINgenius+Foundation+Porcelain+buy", country: "India" },
  { id: "fn_011", name: "Lightening Liquid Foundation Natural", brand: "Wardah", category: "foundation", hexCode: "#E8C99A", red: 232, green: 201, blue: 154, colorName: "Natural", price: 89000, currency: "IDR", retailerUrl: "https://www.google.com/search?q=Wardah+Lightening+Liquid+Foundation+Natural+buy", country: "Indonesia" },
  { id: "fn_012", name: "Skin Tint 01 Fair", brand: "Perfect Diary", category: "foundation", hexCode: "#F5E6D3", red: 245, green: 230, blue: 211, colorName: "Fair", price: 89, currency: "CNY", retailerUrl: "https://www.google.com/search?q=Perfect+Diary+Skin+Tint+01+Fair+buy", country: "China" },
  { id: "fn_013", name: "Make B Foundation Porcelain", brand: "O Boticario", category: "foundation", hexCode: "#F5DEB3", red: 245, green: 222, blue: 179, colorName: "Porcelain", price: 89, currency: "BRL", retailerUrl: "https://www.google.com/search?q=O+Boticario+Make+B+Foundation+Porcelain+buy", country: "Brazil" },
  { id: "fn_014", name: "True Color Foundation Hazelnut", brand: "Black Opal", category: "foundation", hexCode: "#8B6914", red: 139, green: 105, blue: 20, colorName: "Hazelnut", price: 12, currency: "USD", retailerUrl: "https://www.google.com/search?q=Black+Opal+True+Color+Foundation+Hazelnut+buy", country: "Nigeria" },
  { id: "fn_015", name: "Flawless Finish Foundation Ebony", brand: "Zaron", category: "foundation", hexCode: "#4A2C0A", red: 74, green: 44, blue: 10, colorName: "Ebony", price: 3500, currency: "NGN", retailerUrl: "https://www.google.com/search?q=Zaron+Flawless+Finish+Foundation+Ebony+buy", country: "Nigeria" },
  { id: "fn_016", name: "Magic Foundation 3W", brand: "Charlotte Tilbury", category: "foundation", hexCode: "#D4A76A", red: 212, green: 167, blue: 106, colorName: "Medium Warm", price: 50, currency: "USD", retailerUrl: "https://www.google.com/search?q=Charlotte+Tilbury+Magic+Foundation+3W+buy", country: "USA" },
  { id: "fn_017", name: "Double Wear 2C3 Fresco", brand: "Estee Lauder", category: "foundation", hexCode: "#D4A76A", red: 212, green: 167, blue: 106, colorName: "Fresco", price: 52, currency: "USD", retailerUrl: "https://www.google.com/search?q=Estee+Lauder+Double+Wear+2C3+Fresco+buy", country: "USA" },
  { id: "fn_018", name: "Skin Foundation Warm Ivory", brand: "Bobbi Brown", category: "foundation", hexCode: "#F5CBA7", red: 245, green: 203, blue: 167, colorName: "Warm Ivory", price: 48, currency: "USD", retailerUrl: "https://www.google.com/search?q=Bobbi+Brown+Skin+Foundation+Warm+Ivory+buy", country: "USA" },
  { id: "fn_019", name: "Ace of Face Foundation Sand", brand: "Sugar Cosmetics", category: "foundation", hexCode: "#F0D5A8", red: 240, green: 213, blue: 168, colorName: "Sand", price: 699, currency: "INR", retailerUrl: "https://www.google.com/search?q=Sugar+Cosmetics+Ace+of+Face+Foundation+Sand+buy", country: "India" },
  { id: "fn_020", name: "Bare with Me Skin Tint Natural", brand: "Emina", category: "foundation", hexCode: "#E8C99A", red: 232, green: 201, blue: 154, colorName: "Natural", price: 65000, currency: "IDR", retailerUrl: "https://www.google.com/search?q=Emina+Bare+with+Me+Skin+Tint+Natural+buy", country: "Indonesia" },

  // ── NEW CATEGORY: EYELINER ──────────────────────────────────────────────
  { id: "el_001", name: "Eye Kohl Smolder Black", brand: "MAC", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 22, currency: "USD", retailerUrl: "https://www.google.com/search?q=MAC+Eye+Kohl+Smolder+buy", country: "USA" },
  { id: "el_002", name: "Epic Ink Liner Black", brand: "NYX", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 12, currency: "USD", retailerUrl: "https://www.google.com/search?q=NYX+Epic+Ink+Liner+Black+buy", country: "USA" },
  { id: "el_003", name: "24/7 Glide-On Zero", brand: "Urban Decay", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 23, currency: "USD", retailerUrl: "https://www.google.com/search?q=Urban+Decay+24%2F7+Glide-On+Zero+buy", country: "USA" },
  { id: "el_004", name: "Lasting Drama Gel Liner Black", brand: "Maybelline", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Maybelline+Lasting+Drama+Gel+Liner+buy", country: "USA" },
  { id: "el_005", name: "Eyeconic Kajal Black", brand: "Lakme", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 199, currency: "INR", retailerUrl: "https://www.google.com/search?q=Lakme+Eyeconic+Kajal+Black+buy", country: "India" },
  { id: "el_006", name: "Just Smoky Kajal", brand: "Colorbar", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 299, currency: "INR", retailerUrl: "https://www.google.com/search?q=Colorbar+Just+Smoky+Kajal+buy", country: "India" },
  { id: "el_007", name: "EyeXpert Eyeliner Black", brand: "Wardah", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 45000, currency: "IDR", retailerUrl: "https://www.google.com/search?q=Wardah+EyeXpert+Eyeliner+Black+buy", country: "Indonesia" },
  { id: "el_008", name: "Eyeliner 01 Deep Black", brand: "Perfect Diary", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Deep Black", price: 29, currency: "CNY", retailerUrl: "https://www.google.com/search?q=Perfect+Diary+Eyeliner+01+Deep+Black+buy", country: "China" },
  { id: "el_009", name: "Una Lapis Delineador Black", brand: "Natura", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 35, currency: "BRL", retailerUrl: "https://www.google.com/search?q=Natura+Una+Lapis+Delineador+Black+buy", country: "Brazil" },
  { id: "el_010", name: "Eye Kohl Teddy Brown", brand: "MAC", category: "eyeliner", hexCode: "#6B4226", red: 107, green: 66, blue: 38, colorName: "Teddy Brown", price: 22, currency: "USD", retailerUrl: "https://www.google.com/search?q=MAC+Eye+Kohl+Teddy+buy", country: "USA" },
  { id: "el_011", name: "Retractable Eyeliner Espresso", brand: "NYX", category: "eyeliner", hexCode: "#3B1F0A", red: 59, green: 31, blue: 10, colorName: "Espresso", price: 8, currency: "USD", retailerUrl: "https://www.google.com/search?q=NYX+Retractable+Eyeliner+Espresso+buy", country: "USA" },
  { id: "el_012", name: "Floral Engraved Eyeliner Chestnut", brand: "Florasis", category: "eyeliner", hexCode: "#4A2C0A", red: 74, green: 44, blue: 10, colorName: "Chestnut", price: 89, currency: "CNY", retailerUrl: "https://www.google.com/search?q=Florasis+Floral+Engraved+Eyeliner+Chestnut+buy", country: "China" },
  { id: "el_013", name: "Precision Liner Black", brand: "Zaron", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 2500, currency: "NGN", retailerUrl: "https://www.google.com/search?q=Zaron+Precision+Liner+Black+buy", country: "Nigeria" },
  { id: "el_014", name: "Eye Believe Kajal Black", brand: "Plum", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 249, currency: "INR", retailerUrl: "https://www.google.com/search?q=Plum+Eye+Believe+Kajal+Black+buy", country: "India" },
  { id: "el_015", name: "Eye Coach Liner Black", brand: "BLP Beauty", category: "eyeliner", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 89000, currency: "IDR", retailerUrl: "https://www.google.com/search?q=BLP+Beauty+Eye+Coach+Liner+Black+buy", country: "Indonesia" },

  // ── NEW CATEGORY: NAIL POLISH (expanded) ────────────────────────────────
  { id: "np_001", name: "Bubble Bath", brand: "OPI", category: "nail_polish", hexCode: "#F2C4CE", red: 242, green: 196, blue: 206, colorName: "Sheer Pink", price: 11, currency: "USD", retailerUrl: "https://www.google.com/search?q=OPI+Bubble+Bath+nail+polish+buy", country: "USA" },
  { id: "np_002", name: "Malaga Wine", brand: "OPI", category: "nail_polish", hexCode: "#6B2D3E", red: 107, green: 45, blue: 62, colorName: "Deep Burgundy", price: 11, currency: "USD", retailerUrl: "https://www.google.com/search?q=OPI+Malaga+Wine+buy", country: "USA" },
  { id: "np_003", name: "Big Apple Red", brand: "OPI", category: "nail_polish", hexCode: "#CC2936", red: 204, green: 41, blue: 54, colorName: "Classic Red", price: 11, currency: "USD", retailerUrl: "https://www.google.com/search?q=OPI+Big+Apple+Red+buy", country: "USA" },
  { id: "np_004", name: "Ballet Slippers", brand: "Essie", category: "nail_polish", hexCode: "#F4C2C2", red: 244, green: 194, blue: 194, colorName: "Sheer Pink", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Essie+Ballet+Slippers+buy", country: "USA" },
  { id: "np_005", name: "Bordeaux", brand: "Essie", category: "nail_polish", hexCode: "#5C1A2E", red: 92, green: 26, blue: 46, colorName: "Deep Bordeaux", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Essie+Bordeaux+buy", country: "USA" },
  { id: "np_006", name: "Insta-Dri Coral Reef", brand: "Sally Hansen", category: "nail_polish", hexCode: "#FF7F50", red: 255, green: 127, blue: 80, colorName: "Coral", price: 8, currency: "USD", retailerUrl: "https://www.google.com/search?q=Sally+Hansen+Insta-Dri+Coral+Reef+buy", country: "USA" },
  { id: "np_007", name: "True Wear Nail Color Bordeaux", brand: "Lakme", category: "nail_polish", hexCode: "#6B2D3E", red: 107, green: 45, blue: 62, colorName: "Bordeaux", price: 159, currency: "INR", retailerUrl: "https://www.google.com/search?q=Lakme+True+Wear+Nail+Color+Bordeaux+buy", country: "India" },
  { id: "np_008", name: "Ultra HD Gel Polish Cherry", brand: "Revlon", category: "nail_polish", hexCode: "#CC2936", red: 204, green: 41, blue: 54, colorName: "Cherry", price: 9, currency: "USD", retailerUrl: "https://www.google.com/search?q=Revlon+Ultra+HD+Gel+Polish+Cherry+buy", country: "USA" },
  { id: "np_009", name: "Real Color Nail 72 Cherry", brand: "Innisfree", category: "nail_polish", hexCode: "#CC2936", red: 204, green: 41, blue: 54, colorName: "Cherry", price: 45, currency: "CNY", retailerUrl: "https://www.google.com/search?q=Innisfree+Real+Color+Nail+72+Cherry+buy", country: "China" },
  { id: "np_010", name: "Una Esmalte Escarlet", brand: "Natura", category: "nail_polish", hexCode: "#CC2936", red: 204, green: 41, blue: 54, colorName: "Scarlet", price: 25, currency: "BRL", retailerUrl: "https://www.google.com/search?q=Natura+Una+Esmalte+Escarlet+buy", country: "Brazil" },
  { id: "np_011", name: "Colorfit Nail Polish Red Classic", brand: "Wardah", category: "nail_polish", hexCode: "#CC2936", red: 204, green: 41, blue: 54, colorName: "Red Classic", price: 35000, currency: "IDR", retailerUrl: "https://www.google.com/search?q=Wardah+Colorfit+Nail+Polish+Red+Classic+buy", country: "Indonesia" },
  { id: "np_012", name: "So Jelly Nail Polish Strawberry", brand: "Emina", category: "nail_polish", hexCode: "#F4C2C2", red: 244, green: 194, blue: 194, colorName: "Strawberry Pink", price: 25000, currency: "IDR", retailerUrl: "https://www.google.com/search?q=Emina+So+Jelly+Nail+Polish+Strawberry+buy", country: "Indonesia" },
  { id: "np_013", name: "Nail Polish Poppy Red", brand: "Zaron", category: "nail_polish", hexCode: "#CC2936", red: 204, green: 41, blue: 54, colorName: "Poppy Red", price: 1800, currency: "NGN", retailerUrl: "https://www.google.com/search?q=Zaron+Nail+Polish+Poppy+Red+buy", country: "Nigeria" },
  { id: "np_014", name: "Nail Polish Nude Beige", brand: "House of Tara", category: "nail_polish", hexCode: "#D4A76A", red: 212, green: 167, blue: 106, colorName: "Nude Beige", price: 2000, currency: "NGN", retailerUrl: "https://www.google.com/search?q=House+of+Tara+Nail+Polish+Nude+Beige+buy", country: "Nigeria" },
  { id: "np_015", name: "Nail Lacquer Nude", brand: "Colorbar", category: "nail_polish", hexCode: "#D4A76A", red: 212, green: 167, blue: 106, colorName: "Nude", price: 225, currency: "INR", retailerUrl: "https://www.google.com/search?q=Colorbar+Nail+Lacquer+Nude+buy", country: "India" },
  { id: "np_016", name: "Color Therapy Burnished Bronze", brand: "Sally Hansen", category: "nail_polish", hexCode: "#8B6914", red: 139, green: 105, blue: 20, colorName: "Burnished Bronze", price: 8, currency: "USD", retailerUrl: "https://www.google.com/search?q=Sally+Hansen+Color+Therapy+Burnished+Bronze+buy", country: "USA" },
  { id: "np_017", name: "Lincoln Park After Dark", brand: "OPI", category: "nail_polish", hexCode: "#3B1F0A", red: 59, green: 31, blue: 10, colorName: "Dark Plum", price: 11, currency: "USD", retailerUrl: "https://www.google.com/search?q=OPI+Lincoln+Park+After+Dark+buy", country: "USA" },
  { id: "np_018", name: "Midnight Cami", brand: "Essie", category: "nail_polish", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Midnight Black", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Essie+Midnight+Cami+buy", country: "USA" },
  { id: "np_019", name: "Nail Enamel Candy Floss", brand: "Nykaa", category: "nail_polish", hexCode: "#F4C2C2", red: 244, green: 194, blue: 194, colorName: "Candy Floss", price: 149, currency: "INR", retailerUrl: "https://www.google.com/search?q=Nykaa+Nail+Enamel+Candy+Floss+buy", country: "India" },
  { id: "np_020", name: "Nail Lacquer Berry Nice", brand: "Sugar Cosmetics", category: "nail_polish", hexCode: "#6B2D3E", red: 107, green: 45, blue: 62, colorName: "Berry", price: 299, currency: "INR", retailerUrl: "https://www.google.com/search?q=Sugar+Cosmetics+Nail+Lacquer+Berry+Nice+buy", country: "India" },

  // ── NEW CATEGORY: HAIR COLOUR ───────────────────────────────────────────
  { id: "hc_001", name: "Casting Creme Gloss 200 Ebony Black", brand: "L'Oreal", category: "hair_colour", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Ebony Black", price: 12, currency: "USD", retailerUrl: "https://www.google.com/search?q=L%27Oreal+Casting+Creme+Gloss+200+Ebony+Black+buy", country: "USA" },
  { id: "hc_002", name: "Excellence Creme 7 Dark Blonde", brand: "L'Oreal", category: "hair_colour", hexCode: "#C8A951", red: 200, green: 169, blue: 81, colorName: "Dark Blonde", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=L%27Oreal+Excellence+Creme+7+Dark+Blonde+buy", country: "USA" },
  { id: "hc_003", name: "Excellence Creme 4 Dark Brown", brand: "L'Oreal", category: "hair_colour", hexCode: "#4A2C0A", red: 74, green: 44, blue: 10, colorName: "Dark Brown", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=L%27Oreal+Excellence+Creme+4+Dark+Brown+buy", country: "USA" },
  { id: "hc_004", name: "Color Charm 3N Dark Brown", brand: "Wella", category: "hair_colour", hexCode: "#3B1F0A", red: 59, green: 31, blue: 10, colorName: "Dark Brown", price: 9, currency: "USD", retailerUrl: "https://www.google.com/search?q=Wella+Color+Charm+3N+Dark+Brown+buy", country: "USA" },
  { id: "hc_005", name: "Color Charm 7N Dark Blonde", brand: "Wella", category: "hair_colour", hexCode: "#C8A951", red: 200, green: 169, blue: 81, colorName: "Dark Blonde", price: 9, currency: "USD", retailerUrl: "https://www.google.com/search?q=Wella+Color+Charm+7N+Dark+Blonde+buy", country: "USA" },
  { id: "hc_006", name: "Keratin Color 1.0 Midnight Black", brand: "Schwarzkopf", category: "hair_colour", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Midnight Black", price: 12, currency: "USD", retailerUrl: "https://www.google.com/search?q=Schwarzkopf+Keratin+Color+1.0+Midnight+Black+buy", country: "USA" },
  { id: "hc_007", name: "Keratin Color 6.0 Light Brown", brand: "Schwarzkopf", category: "hair_colour", hexCode: "#8B6914", red: 139, green: 105, blue: 20, colorName: "Light Brown", price: 12, currency: "USD", retailerUrl: "https://www.google.com/search?q=Schwarzkopf+Keratin+Color+6.0+Light+Brown+buy", country: "USA" },
  { id: "hc_008", name: "Nutrisse 40 Dark Brown", brand: "Garnier", category: "hair_colour", hexCode: "#3B1F0A", red: 59, green: 31, blue: 10, colorName: "Dark Brown", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Garnier+Nutrisse+40+Dark+Brown+buy", country: "USA" },
  { id: "hc_009", name: "Nutrisse 60 Light Natural Brown", brand: "Garnier", category: "hair_colour", hexCode: "#8B6914", red: 139, green: 105, blue: 20, colorName: "Light Natural Brown", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Garnier+Nutrisse+60+Light+Natural+Brown+buy", country: "USA" },
  { id: "hc_010", name: "Colorsilk 10 Black", brand: "Revlon", category: "hair_colour", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 7, currency: "USD", retailerUrl: "https://www.google.com/search?q=Revlon+Colorsilk+10+Black+buy", country: "USA" },
  { id: "hc_011", name: "Nice n Easy 4 Dark Brown", brand: "Clairol", category: "hair_colour", hexCode: "#3B1F0A", red: 59, green: 31, blue: 10, colorName: "Dark Brown", price: 9, currency: "USD", retailerUrl: "https://www.google.com/search?q=Clairol+Nice+n+Easy+4+Dark+Brown+buy", country: "USA" },
  { id: "hc_012", name: "Speedy Hair Color Black", brand: "Bigen", category: "hair_colour", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 199, currency: "INR", retailerUrl: "https://www.google.com/search?q=Bigen+Speedy+Hair+Color+Black+buy", country: "India" },
  { id: "hc_013", name: "Hair Colour Dark Brown", brand: "Streax", category: "hair_colour", hexCode: "#3B1F0A", red: 59, green: 31, blue: 10, colorName: "Dark Brown", price: 299, currency: "INR", retailerUrl: "https://www.google.com/search?q=Streax+Hair+Colour+Dark+Brown+buy", country: "India" },
  { id: "hc_014", name: "Color Naturals Shade 1 Black", brand: "Garnier", category: "hair_colour", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 199, currency: "INR", retailerUrl: "https://www.google.com/search?q=Garnier+Color+Naturals+Shade+1+Black+buy+India", country: "India" },
  { id: "hc_015", name: "Fade Resist Rich Conditioning Color Jet Black", brand: "Dark and Lovely", category: "hair_colour", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Jet Black", price: 3500, currency: "NGN", retailerUrl: "https://www.google.com/search?q=Dark+and+Lovely+Fade+Resist+Jet+Black+buy", country: "Nigeria" },
  { id: "hc_016", name: "Fade Resist Auburn Brown", brand: "Dark and Lovely", category: "hair_colour", hexCode: "#8B3A3A", red: 139, green: 58, blue: 58, colorName: "Auburn Brown", price: 3500, currency: "NGN", retailerUrl: "https://www.google.com/search?q=Dark+and+Lovely+Fade+Resist+Auburn+Brown+buy", country: "Nigeria" },
  { id: "hc_017", name: "Feria Midnight Black", brand: "L'Oreal Paris", category: "hair_colour", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Midnight Black", price: 12, currency: "USD", retailerUrl: "https://www.google.com/search?q=L%27Oreal+Feria+Midnight+Black+buy", country: "USA" },
  { id: "hc_018", name: "Koleston Perfect 55/0 Light Brown", brand: "Wella", category: "hair_colour", hexCode: "#8B6914", red: 139, green: 105, blue: 20, colorName: "Light Brown", price: 15, currency: "USD", retailerUrl: "https://www.google.com/search?q=Wella+Koleston+Perfect+55%2F0+Light+Brown+buy", country: "USA" },
  { id: "hc_019", name: "Igora Royal 6-0 Dark Blonde", brand: "Schwarzkopf", category: "hair_colour", hexCode: "#C8A951", red: 200, green: 169, blue: 81, colorName: "Dark Blonde", price: 18, currency: "USD", retailerUrl: "https://www.google.com/search?q=Schwarzkopf+Igora+Royal+6-0+Dark+Blonde+buy", country: "USA" },
  { id: "hc_020", name: "Topchic 6N Dark Blonde", brand: "Goldwell", category: "hair_colour", hexCode: "#C8A951", red: 200, green: 169, blue: 81, colorName: "Dark Blonde", price: 16, currency: "USD", retailerUrl: "https://www.google.com/search?q=Goldwell+Topchic+6N+Dark+Blonde+buy", country: "USA" },
  { id: "hc_021", name: "Hair Color Black", brand: "Makarizo", category: "hair_colour", hexCode: "#1C1C1E", red: 28, green: 28, blue: 30, colorName: "Black", price: 45000, currency: "IDR", retailerUrl: "https://www.google.com/search?q=Makarizo+Hair+Color+Black+buy", country: "Indonesia" },
  { id: "hc_022", name: "Bubble Hair Color Milk Tea Brown", brand: "Liese", category: "hair_colour", hexCode: "#C8A951", red: 200, green: 169, blue: 81, colorName: "Milk Tea Brown", price: 89, currency: "CNY", retailerUrl: "https://www.google.com/search?q=Liese+Bubble+Hair+Color+Milk+Tea+Brown+buy", country: "China" },
  { id: "hc_023", name: "Color Expert Dark Brown", brand: "Schwarzkopf", category: "hair_colour", hexCode: "#3B1F0A", red: 59, green: 31, blue: 10, colorName: "Dark Brown", price: 45, currency: "BRL", retailerUrl: "https://www.google.com/search?q=Schwarzkopf+Color+Expert+Dark+Brown+buy+Brazil", country: "Brazil" },
  { id: "hc_024", name: "Total Color Deep Brown", brand: "Revlon", category: "hair_colour", hexCode: "#4A2C0A", red: 74, green: 44, blue: 10, colorName: "Deep Brown", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Revlon+Total+Color+Deep+Brown+buy", country: "Australia" },
  { id: "hc_025", name: "Natural Instincts Dark Brown", brand: "Clairol", category: "hair_colour", hexCode: "#3B1F0A", red: 59, green: 31, blue: 10, colorName: "Dark Brown", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Clairol+Natural+Instincts+Dark+Brown+buy", country: "Australia" },

  // ── NEW CATEGORY: CONCEALER ─────────────────────────────────────────────
  { id: "cc_001", name: "Pro Filt'r Concealer 130W", brand: "Fenty Beauty", category: "concealer", hexCode: "#F5CBA7", red: 245, green: 203, blue: 167, colorName: "Light Warm", price: 26, currency: "USD", retailerUrl: "https://www.google.com/search?q=Fenty+Beauty+Pro+Filtr+Concealer+130W+buy", country: "USA" },
  { id: "cc_002", name: "Pro Filt'r Concealer 420N", brand: "Fenty Beauty", category: "concealer", hexCode: "#8B6914", red: 139, green: 105, blue: 20, colorName: "Deep Neutral", price: 26, currency: "USD", retailerUrl: "https://www.google.com/search?q=Fenty+Beauty+Pro+Filtr+Concealer+420N+buy", country: "USA" },
  { id: "cc_003", name: "Radiant Creamy Concealer Vanilla", brand: "NARS", category: "concealer", hexCode: "#F5DEB3", red: 245, green: 222, blue: 179, colorName: "Vanilla", price: 32, currency: "USD", retailerUrl: "https://www.google.com/search?q=NARS+Radiant+Creamy+Concealer+Vanilla+buy", country: "USA" },
  { id: "cc_004", name: "Studio Fix Concealer NC20", brand: "MAC", category: "concealer", hexCode: "#F5CBA7", red: 245, green: 203, blue: 167, colorName: "Light Neutral", price: 26, currency: "USD", retailerUrl: "https://www.google.com/search?q=MAC+Studio+Fix+Concealer+NC20+buy", country: "USA" },
  { id: "cc_005", name: "Fit Me Concealer 10 Light", brand: "Maybelline", category: "concealer", hexCode: "#F5E6D3", red: 245, green: 230, blue: 211, colorName: "Light", price: 8, currency: "USD", retailerUrl: "https://www.google.com/search?q=Maybelline+Fit+Me+Concealer+10+Light+buy", country: "USA" },
  { id: "cc_006", name: "Fit Me Concealer 40 Caramel", brand: "Maybelline", category: "concealer", hexCode: "#C68642", red: 198, green: 134, blue: 66, colorName: "Caramel", price: 8, currency: "USD", retailerUrl: "https://www.google.com/search?q=Maybelline+Fit+Me+Concealer+40+Caramel+buy", country: "USA" },
  { id: "cc_007", name: "Absolute White Intense Concealer Ivory", brand: "Lakme", category: "concealer", hexCode: "#F5E6D3", red: 245, green: 230, blue: 211, colorName: "Ivory", price: 499, currency: "INR", retailerUrl: "https://www.google.com/search?q=Lakme+Absolute+White+Intense+Concealer+Ivory+buy", country: "India" },
  { id: "cc_008", name: "Ace of Face Concealer Sand", brand: "Sugar Cosmetics", category: "concealer", hexCode: "#F0D5A8", red: 240, green: 213, blue: 168, colorName: "Sand", price: 599, currency: "INR", retailerUrl: "https://www.google.com/search?q=Sugar+Cosmetics+Ace+of+Face+Concealer+Sand+buy", country: "India" },
  { id: "cc_009", name: "Lightening Concealer Natural", brand: "Wardah", category: "concealer", hexCode: "#E8C99A", red: 232, green: 201, blue: 154, colorName: "Natural", price: 75000, currency: "IDR", retailerUrl: "https://www.google.com/search?q=Wardah+Lightening+Concealer+Natural+buy", country: "Indonesia" },
  { id: "cc_010", name: "Concealer 01 Porcelain", brand: "Perfect Diary", category: "concealer", hexCode: "#F5E6D3", red: 245, green: 230, blue: 211, colorName: "Porcelain", price: 69, currency: "CNY", retailerUrl: "https://www.google.com/search?q=Perfect+Diary+Concealer+01+Porcelain+buy", country: "China" },
  { id: "cc_011", name: "True Color Concealer Hazelnut", brand: "Black Opal", category: "concealer", hexCode: "#8B6914", red: 139, green: 105, blue: 20, colorName: "Hazelnut", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Black+Opal+True+Color+Concealer+Hazelnut+buy", country: "Nigeria" },
  { id: "cc_012", name: "Perfect Concealer Ebony", brand: "Zaron", category: "concealer", hexCode: "#4A2C0A", red: 74, green: 44, blue: 10, colorName: "Ebony", price: 2800, currency: "NGN", retailerUrl: "https://www.google.com/search?q=Zaron+Perfect+Concealer+Ebony+buy", country: "Nigeria" },
  { id: "cc_013", name: "Make B Concealer Porcelain", brand: "O Boticario", category: "concealer", hexCode: "#F5DEB3", red: 245, green: 222, blue: 179, colorName: "Porcelain", price: 65, currency: "BRL", retailerUrl: "https://www.google.com/search?q=O+Boticario+Make+B+Concealer+Porcelain+buy", country: "Brazil" },
  { id: "cc_014", name: "Magic Away Concealer 3", brand: "Charlotte Tilbury", category: "concealer", hexCode: "#D4A76A", red: 212, green: 167, blue: 106, colorName: "Medium", price: 36, currency: "USD", retailerUrl: "https://www.google.com/search?q=Charlotte+Tilbury+Magic+Away+Concealer+3+buy", country: "USA" },
  { id: "cc_015", name: "Revealer Concealer 3.5W", brand: "Kosas", category: "concealer", hexCode: "#D4A76A", red: 212, green: 167, blue: 106, colorName: "Medium Warm", price: 30, currency: "USD", retailerUrl: "https://www.google.com/search?q=Kosas+Revealer+Concealer+3.5W+buy", country: "USA" },

  // ── NEW CATEGORY: TINTED SUNSCREEN ──────────────────────────────────────
  { id: "ts_001", name: "Pro Filt'r Soft Matte SPF30 130W", brand: "Fenty Beauty", category: "tinted_sunscreen", hexCode: "#F5CBA7", red: 245, green: 203, blue: 167, colorName: "Light Warm", price: 29, currency: "USD", retailerUrl: "https://www.google.com/search?q=Fenty+Beauty+Pro+Filtr+Soft+Matte+SPF30+130W+buy", country: "USA" },
  { id: "ts_002", name: "Pure Radiant Tinted Moisturizer SPF30 Finland", brand: "NARS", category: "tinted_sunscreen", hexCode: "#F5DEB3", red: 245, green: 222, blue: 179, colorName: "Finland", price: 46, currency: "USD", retailerUrl: "https://www.google.com/search?q=NARS+Pure+Radiant+Tinted+Moisturizer+SPF30+Finland+buy", country: "USA" },
  { id: "ts_003", name: "Tinted Moisturizer SPF20 Nude", brand: "Laura Mercier", category: "tinted_sunscreen", hexCode: "#F5CBA7", red: 245, green: 203, blue: 167, colorName: "Nude", price: 50, currency: "USD", retailerUrl: "https://www.google.com/search?q=Laura+Mercier+Tinted+Moisturizer+SPF20+Nude+buy", country: "USA" },
  { id: "ts_004", name: "Healthy Skin Tinted Sunscreen SPF30 Light", brand: "Neutrogena", category: "tinted_sunscreen", hexCode: "#F5E6D3", red: 245, green: 230, blue: 211, colorName: "Light", price: 16, currency: "USD", retailerUrl: "https://www.google.com/search?q=Neutrogena+Healthy+Skin+Tinted+Sunscreen+SPF30+Light+buy", country: "USA" },
  { id: "ts_005", name: "Sun Expert Tinted Sunscreen SPF50 Natural", brand: "Lakme", category: "tinted_sunscreen", hexCode: "#E8C99A", red: 232, green: 201, blue: 154, colorName: "Natural", price: 349, currency: "INR", retailerUrl: "https://www.google.com/search?q=Lakme+Sun+Expert+Tinted+Sunscreen+SPF50+Natural+buy", country: "India" },
  { id: "ts_006", name: "WhiteGlow SPF25 Tinted Serum", brand: "Lotus Herbals", category: "tinted_sunscreen", hexCode: "#F5E6D3", red: 245, green: 230, blue: 211, colorName: "Light", price: 399, currency: "INR", retailerUrl: "https://www.google.com/search?q=Lotus+Herbals+WhiteGlow+SPF25+Tinted+Serum+buy", country: "India" },
  { id: "ts_007", name: "UV Shield Tinted Sunscreen Natural", brand: "Wardah", category: "tinted_sunscreen", hexCode: "#E8C99A", red: 232, green: 201, blue: 154, colorName: "Natural", price: 95000, currency: "IDR", retailerUrl: "https://www.google.com/search?q=Wardah+UV+Shield+Tinted+Sunscreen+Natural+buy", country: "Indonesia" },
  { id: "ts_008", name: "UV Aqua Rich Tinted Sunscreen", brand: "Biore", category: "tinted_sunscreen", hexCode: "#F5E6D3", red: 245, green: 230, blue: 211, colorName: "Light", price: 89, currency: "CNY", retailerUrl: "https://www.google.com/search?q=Biore+UV+Aqua+Rich+Tinted+Sunscreen+buy", country: "China" },
  { id: "ts_009", name: "Tinted Sunscreen SPF30 Medium", brand: "Neutrogena", category: "tinted_sunscreen", hexCode: "#D4A76A", red: 212, green: 167, blue: 106, colorName: "Medium", price: 16, currency: "USD", retailerUrl: "https://www.google.com/search?q=Neutrogena+Tinted+Sunscreen+SPF30+Medium+buy", country: "Australia" },
  { id: "ts_010", name: "Tinted SPF30", brand: "Black Girl Sunscreen", category: "tinted_sunscreen", hexCode: "#8B6914", red: 139, green: 105, blue: 20, colorName: "Deep", price: 20, currency: "USD", retailerUrl: "https://www.google.com/search?q=Black+Girl+Sunscreen+Tinted+SPF30+buy", country: "USA" },
  { id: "ts_011", name: "Glowscreen SPF40 Sheer", brand: "Supergoop", category: "tinted_sunscreen", hexCode: "#F5E6D3", red: 245, green: 230, blue: 211, colorName: "Sheer", price: 38, currency: "USD", retailerUrl: "https://www.google.com/search?q=Supergoop+Glowscreen+SPF40+buy", country: "USA" },
  { id: "ts_012", name: "SPF50 Tinted Sunscreen Natural", brand: "Bondi Sands", category: "tinted_sunscreen", hexCode: "#E8C99A", red: 232, green: 201, blue: 154, colorName: "Natural", price: 18, currency: "USD", retailerUrl: "https://www.google.com/search?q=Bondi+Sands+SPF50+Tinted+Sunscreen+Natural+buy", country: "Australia" },

  // ── NEW CATEGORY: MINERAL POWDER / CORRECTIVE COVERAGE ──────────────────
  { id: "mp_001", name: "Original Loose Powder Foundation Fair", brand: "bareMinerals", category: "mineral_powder", hexCode: "#F5E6D3", red: 245, green: 230, blue: 211, colorName: "Fair", price: 32, currency: "USD", retailerUrl: "https://www.google.com/search?q=bareMinerals+Original+Loose+Powder+Foundation+Fair+buy", country: "USA" },
  { id: "mp_002", name: "Original Loose Powder Foundation Medium", brand: "bareMinerals", category: "mineral_powder", hexCode: "#D4A76A", red: 212, green: 167, blue: 106, colorName: "Medium", price: 32, currency: "USD", retailerUrl: "https://www.google.com/search?q=bareMinerals+Original+Loose+Powder+Foundation+Medium+buy", country: "USA" },
  { id: "mp_003", name: "CC+ Cream SPF50 Light", brand: "IT Cosmetics", category: "mineral_powder", hexCode: "#F5CBA7", red: 245, green: 203, blue: 167, colorName: "Light", price: 40, currency: "USD", retailerUrl: "https://www.google.com/search?q=IT+Cosmetics+CC+Cream+SPF50+Light+buy", country: "USA" },
  { id: "mp_004", name: "CC+ Cream SPF50 Deep", brand: "IT Cosmetics", category: "mineral_powder", hexCode: "#8B6914", red: 139, green: 105, blue: 20, colorName: "Deep", price: 40, currency: "USD", retailerUrl: "https://www.google.com/search?q=IT+Cosmetics+CC+Cream+SPF50+Deep+buy", country: "USA" },
  { id: "mp_005", name: "Cover Creme Full Coverage Foundation Beige", brand: "Dermablend", category: "mineral_powder", hexCode: "#D4A76A", red: 212, green: 167, blue: 106, colorName: "Beige", price: 40, currency: "USD", retailerUrl: "https://www.google.com/search?q=Dermablend+Cover+Creme+Beige+buy", country: "USA" },
  { id: "mp_006", name: "Cover Creme Chestnut Brown", brand: "Dermablend", category: "mineral_powder", hexCode: "#6B4226", red: 107, green: 66, blue: 38, colorName: "Chestnut Brown", price: 40, currency: "USD", retailerUrl: "https://www.google.com/search?q=Dermablend+Cover+Creme+Chestnut+Brown+buy", country: "USA" },
  { id: "mp_007", name: "Even Better Makeup SPF15 Fair", brand: "Clinique", category: "mineral_powder", hexCode: "#F5E6D3", red: 245, green: 230, blue: 211, colorName: "Fair", price: 31, currency: "USD", retailerUrl: "https://www.google.com/search?q=Clinique+Even+Better+Makeup+SPF15+Fair+buy", country: "USA" },
  { id: "mp_008", name: "No Color Powder", brand: "RCMA", category: "mineral_powder", hexCode: "#F5F0E8", red: 245, green: 240, blue: 232, colorName: "Translucent", price: 14, currency: "USD", retailerUrl: "https://www.google.com/search?q=RCMA+No+Color+Powder+buy", country: "USA" },
  { id: "mp_009", name: "Color Splurge Pressed Powder Ebony Brown", brand: "Black Opal", category: "mineral_powder", hexCode: "#4A2C0A", red: 74, green: 44, blue: 10, colorName: "Ebony Brown", price: 10, currency: "USD", retailerUrl: "https://www.google.com/search?q=Black+Opal+Color+Splurge+Pressed+Powder+Ebony+Brown+buy", country: "Nigeria" },
  { id: "mp_010", name: "Absolute White Intense Wet & Dry Compact Natural", brand: "Lakme", category: "mineral_powder", hexCode: "#E8C99A", red: 232, green: 201, blue: 154, colorName: "Natural", price: 449, currency: "INR", retailerUrl: "https://www.google.com/search?q=Lakme+Absolute+White+Intense+Wet+Dry+Compact+Natural+buy", country: "India" },
  { id: "mp_011", name: "Exclusive Creamy Foundation Natural Beige", brand: "Wardah", category: "mineral_powder", hexCode: "#E8C99A", red: 232, green: 201, blue: 154, colorName: "Natural Beige", price: 89000, currency: "IDR", retailerUrl: "https://www.google.com/search?q=Wardah+Exclusive+Creamy+Foundation+Natural+Beige+buy", country: "Indonesia" },
  { id: "mp_012", name: "Po Compacto Mineral Natural", brand: "Vult", category: "mineral_powder", hexCode: "#D4A76A", red: 212, green: 167, blue: 106, colorName: "Natural", price: 45, currency: "BRL", retailerUrl: "https://www.google.com/search?q=Vult+Po+Compacto+Mineral+Natural+buy", country: "Brazil" },
];

const COUNTRY_ALIASES = { 'Australia': 'USA' };

function findColorMatches(r, g, b, country, category = null, limit = 10) {
  let pool = PRODUCTS;
  const resolvedCountry = COUNTRY_ALIASES[country] || country;
  if (resolvedCountry) pool = pool.filter(p => p.country === resolvedCountry);
  if (pool.length === 0) pool = PRODUCTS;
  if (category) pool = pool.filter(p => p.category === category);
  return pool
    .map(p => ({
      ...p,
      colorDistance: Math.round(Math.sqrt((r - p.red) ** 2 + (g - p.green) ** 2 + (b - p.blue) ** 2))
    }))
    .sort((a, b) => a.colorDistance - b.colorDistance)
    .slice(0, limit);
}

function findMoreMatches(r, g, b, country, category = null, skip = 10, limit = 5) {
  let pool = PRODUCTS;
  const resolvedCountry = COUNTRY_ALIASES[country] || country;
  if (resolvedCountry) pool = pool.filter(p => p.country === resolvedCountry);
  if (pool.length === 0) pool = PRODUCTS;
  if (category) pool = pool.filter(p => p.category === category);
  return pool
    .map(p => ({ ...p, colorDistance: Math.round(Math.sqrt((r - p.red) ** 2 + (g - p.green) ** 2 + (b - p.blue) ** 2)) }))
    .sort((a, b) => a.colorDistance - b.colorDistance)
    .slice(skip, skip + limit);
}

export default function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { r, g, b, country, category, skip, limit } = req.body;

    if (r === undefined || g === undefined || b === undefined) {
      return res.status(400).json({ error: 'Missing r, g, b values' });
    }

    let matches;
    if (skip !== undefined) {
      matches = findMoreMatches(r, g, b, country, category, skip, limit || 5);
    } else {
      matches = findColorMatches(r, g, b, country, category, limit || 10);
    }

    // Convert USD to AUD for Australian users
    if (country === 'Australia') {
      matches = matches.map(p => ({
        ...p,
        price: p.currency === 'USD' ? Math.round(p.price * 1.55 * 100) / 100 : p.price,
        currency: p.currency === 'USD' ? 'AUD' : p.currency,
      }));
    }

    return res.status(200).json({ matches });
  } catch (err) {
    return res.status(500).json({ error: err.message || 'Internal server error' });
  }
}
